### ISSUE TITLE
Login as homepage screen

### ISSUE THREAD

**Issue by LeCitrus** [CMPUT301F22T08/AndroidImpact#112]
Instead of a homepage with hyperlinks, the homepage is a login screen. Tutorial on youtube?

**Comment by joshuanianji** [comment]
Related to #86

**Comment by LeCitrus** [comment]
https://www.youtube.com/watch?v=tbh9YaWPKKs

**Comment by LeCitrus** [comment]
https://firebase.google.com/docs/auth/android/start

**Comment by LeCitrus** [comment]
We will also have to add a logout button somewhere, maybe in the action bar

**Comment by ajsingh1012** [comment]
This should be done now with #164, but we still need to test this.

**Comment by LeCitrus** [comment]
Yup its good!
