### ISSUE TITLE
Show recipe comments and ingredients with dropdown box

### ISSUE THREAD

**Issue by LeCitrus** [CMPUT301F22T08/AndroidImpact#137]

**Comment by joshuanianji** [comment]
I did a similar dropdown with Ingredients, so I can take a shot at this.

**Comment by joshuanianji** [comment]
Was working on this in the [`recipe-dropdown`](https://github.com/CMPUT301F22T08/AndroidImpact/tree/recipe-dropdown) but it kept making weird errors
