### ISSUE TITLE
Testing: Switch to Espresso?

### ISSUE THREAD

**Issue by joshuanianji** [CMPUT301F22T08/AndroidImpact#41]
Robotium [has not been updated in 6 years](https://github.com/RobotiumTech/robotium), while Espresso is [regularly maintained by Google](https://developer.android.com/training/testing/espresso). Do these tools cover the same domain, or do we still need Robotium?

**Comment by LeCitrus** [comment]
I think we should start with robotium since we learned it in lab participation, and if we have time we can try espresso.

**Comment by vedudx** [comment]
I agree with Curtis owing to deadlines. But finishing this lab also makes me wonder if it is better to switch to expresso as it might be helpful in long term even though it will take some time to learn

**Comment by kailashs2002** [comment]
Yeah sicne we only have about 2 weeks to the part 3 deadline, I think it would be better to work with robotium for now. We can try experiment with espresso for project part 4 since we have more time to work on it

**Comment by joshuanianji** [comment]
Alright, thanks for the feedback! I'll keep this issue open in case we need to refer to it in a later milestone.

**Comment by joshuanianji** [comment]
Update: this is becoming a bit of a tangled mess. 

1. I'm trying to test out `addStoreIngredient`, which upgraded from a `DatePicker` to an `EditText` with `DatepickerDialog` - fixed by @kailashs2002 d13a6be640a1d5aff2b4d82cb57c17bfe26547a7. 
2. This new change is breaking `addIngredientSuccess` CI tests (somehow differently on my computer and on CI) - #54 
3. BUT: testing a [DatePickerDialog is really annoying](https://www.theinvasionofsmallcubes.com/posts/2013-10-30-testing-a-datapickerdialog-in-android-with-robolectric), and all resources on Robotium are also like 6-15 years old.

At least with Espresso, DatePickerDialog tests are [somewhat possible](https://stackoverflow.com/questions/44835094/check-datepicker-calendar-value-in-android-espresso-framework). Not sure if it's possible to integrate both of them in one project, though.

**Comment by joshuanianji** [comment]
Based on the inactivity of Robotium and some TA feedback, we have decided to move to Espresso.
