### ISSUE TITLE
US 01.01.01 - Add Tests

### ISSUE THREAD

**Issue by joshuanianji** [CMPUT301F22T08/AndroidImpact#43]
Adding tests to #9

**Comment by joshuanianji** [comment]
@kailashs2002 #42 is ready for review, can you check it out?

**Comment by joshuanianji** [comment]
Hmm, a PR would be better instead of an issue. Closing...

**Comment by LeCitrus** [comment]
Hey guys, TA told us to leave finished user stories as in review, so if there are additional requirements later on we don't forget about it

**Comment by joshuanianji** [comment]
Hey @LeCitrus, this isn't a user story so I think it's okay to reclose this. Is that okay?

**Comment by LeCitrus** [comment]
@joshuanianji I see, I did not catch that, thanks for confirming! Closing the issue.
