### ISSUE TITLE
Deployment of Webhook so we get discord message for any PR merge

### ISSUE THREAD

**Issue by vedudx** [CMPUT301F22T08/AndroidImpact#45]
Me and Joshua discussed this idea and we think it will be a great addition to our server as it will help us track PR merges more effectively. Thoughts on this?

**Comment by joshuanianji** [comment]
I think this is a good idea, i can try to work on it with you @vedudx

**Comment by vedudx** [comment]
Sure

**Comment by joshuanianji** [comment]
Here's an example of a webhook I used in a previous project:

https://github.com/joshuanianji/MLH-portfolio-site/blob/main/.github/workflows/webhook-test.yml

**Comment by joshuanianji** [comment]
@vedudx #46 is ready to merge, once you look over it you can go ahead and merge!
