### ISSUE TITLE
MVC Architecture + Firebase

### ISSUE THREAD

**Issue by kailashs2002** [CMPUT301F22T08/AndroidImpact#48]
How should we handle the population from the Firestore? 

I was thinking of defining a public `populateStorage(collection)` method in`IngredientStorage` so we can use that to pull the data from the database and into the storage. 
This would prevent our Activities from being cluttered with Firestore code.
It does, however, mean we have to implement these functions inside all other contianers like `Recipe` and `MealPlan`.

Alternatively, we could implement this into just `Ingredient`/`StoreIngredient` and `Recipe` and call the populate function within main activity for every page in the collection.

How do you guys think we should approach this?

**Comment by vedudx** [comment]
Sounds good. We will need to also implement delete method which deletes from firebase or alternatively a clear method which clears firebase and say if we want to delete something we just delete it from ingredient storage and clear firebase and then populate firebase again.
We can decide whichever method seems better

**Comment by joshuanianji** [comment]
I like this approach as well. To further generalize this, we can make `FirebaseCollectable` interface that defines a `getFromFirestore` or `populateStorage` method, which we can add to `IngredientStorage` and `RecipeStorage`.

**Comment by joshuanianji** [comment]
From the MVC stuff I've been reading, I think we might end up making our controller be in charge of firebase stuff. 

For example, the `IngredientStorage` class will only store data, the `IngredientStorageController` will expose an interface to edit the data (and it will also have a `FirebaseFirestore` attribute to make it sync with firebase).

This might mean the `IngredientStorageActivity` will have the `IngredientStorageController` but not the `IngredientStorage` class directly. 

What do you guys think? I'm not sure if my understanding of MVC is right or not. I do see how this architecture is easier to test than our current one.

**Comment by LeCitrus** [comment]
I think you're mostly right Josh, one thing is that from this website https://www.geeksforgeeks.org/mvc-model-view-controller-architecture-pattern-in-android-with-example/ it says that models communicate with the database as well.

**Comment by kailashs2002** [comment]
This image from that article talks about how controller updates the view and the data in the model, but the view pulls data from the model itself. If the view is pulling data from the model. In that case, what exactly is the controller updating in the view? Does it help specify what data the View should be pulling fromt he model?

![image](https://user-images.githubusercontent.com/87671876/199387663-0994bc77-6c20-4053-bb38-d1c1b73063a8.png)

Also from the looks of the example, the MainActivity is the controller in this case, do we need a separate controller class or can we just use our Fragments as the controller class?

**Comment by kailashs2002** [comment]
Also is it just me, or do these 2 approaches from the GeeksForGeeks say the same thing?
 - *Approach 1:* Activities and fragments can perform the role of Controller and are responsible for updating the View.
 - *Approach 2:* Use activity or fragments as views and controller while Model will be a separate class that does not extend any Android class.

**Comment by kailashs2002** [comment]
[This](https://www.freecodecamp.org/news/the-model-view-controller-pattern-mvc-architecture-and-frameworks-explained/) link from FreeCodeCamp claims that the View and model should not interact in any way at all, and that the controller class only acts as a medium for which data moves through the app layers. 
This system is a lot less confusing than the ones I've looked at so far, and I think thats what our Fragments do already so we may not need separate controller classes.

**Comment by kailashs2002** [comment]
Most articles talk about how the model just holds the data and populates the view to be interacted with by the user. Apparently, the controller is supposed to update the data, depending on what the user wants, forming a sort of feedback loop for the user. From what I understand, our `IngredientStorage` just acts as an array of `StoreIngredient` objects, and the controller, which may or may not be the Activity in this case, goes in to sort the array from the outside, which seems a bit counterintuitive since we can implemment the sorting inside the object itself and call it with a sort_by param. 

In this case, a separate controller class would make more sense than Activity, but it seems to do exactly what we would expect from `IngredientStorage`. So I think it would be safe to say that our Fragments can be our controller classes in this unless Brij thinks otherwise.

**Comment by joshuanianji** [comment]
Thanks for the discussion Kailash! I still don't really understand why the controller is better suited to be a separate class, i feel like making the controller the activity or fragment is better. The [sketchy geeksforgeeks article](https://www.geeksforgeeks.org/mvc-model-view-controller-architecture-pattern-in-android-with-example/) curtis linked above also uses the MainActivity as the controller (although is vague on what the Observable and Observer classes are).

For the sorting isue you said, can't the controller class just call some sort of `IngredientStorage.sort_by` method? It will stil respect the roles that the Model doesn't know of the existence of the Controller, and the Controller updates the Model directly.

**Comment by joshuanianji** [comment]
Renaming this to MVC Architecture and Firebase for better clarity, note that this directly impacts how we deal with #72
