### ISSUE TITLE
Questions for Dr Wong

### ISSUE THREAD

**Issue by vedudx** [CMPUT301F22T08/AndroidImpact#50]
I will email dr Wong for clarification about some questions. If you guys have any questions leave it as a comment here, and I'll make sure to ask those questions in my email too.

**Comment by joshuanianji** [comment]
Questions from #12 (Ingredient Detailed view)
- Should the detailed ingredient view be a fragment or a "show more" dropdown? Or should this be an entirely new activity?
- Should the editing button be in the detailed view or list view

**Comment by joshuanianji** [comment]
Closing now, this issue is done
