### ISSUE TITLE
Ingredient Storage UI upgrade

### ISSUE THREAD

**Issue by kailashs2002** [CMPUT301F22T08/AndroidImpact#52]
Im creating a new branch, IngredientStorageUI, so I can clean up the xml files needed for IngredientStorage so it looks nicer, and also change up the colours so it's more consistent with our mockups

**Comment by joshuanianji** [comment]
Awesome, Thanks Kailash!

**Comment by joshuanianji** [comment]
This was actually closed by #58, but we forgot to link it. Closing...
