### ISSUE TITLE
Bad CI Workflow - Implement Environments?

### ISSUE THREAD

**Issue by joshuanianji** [CMPUT301F22T08/AndroidImpact#57]
CI IS PUSHING CHANGES TO PRODUCTION FIRESTORE AHHHH

**Comment by kailashs2002** [comment]
Who doesnt have an infinite number of eggs in their fridge?

**Comment by kailashs2002** [comment]
If you are referring to that, it shouldn't be too big of an issue once we implement deletion from firestore.

Once add tests to delete the added ingredients (after we finalize issue #48 with everyone about how we connect firestore to the data structures in the app), we can clear the firestore and start adding data from scratch.

**Comment by joshuanianji** [comment]
Yeah, no one's using our app right now so it's not a big deal. I think it's fine to not fix this and just implement delete later on.

The only way to fix this (from what i can think of) is either to make a new project just for testing purposes (which [is what firebase recommends](https://firebase.google.com/docs/projects/dev-workflows/overview-environments)).

So I guess the question is - should we implement these multiple environments? Is it worth our time?

**Comment by joshuanianji** [comment]
Removing `risk high` label, it's not really a risk here. I'll keep this open for now, but might close this later. 

I do think that implementing different environments will make us stand out. I'll add a `feature ideas` label as well.

**Comment by joshuanianji** [comment]
[Firebase Emulator Suite](https://firebase.google.com/docs/emulator-suite) seems pretty easy, I think I can add this to the CI without much discrepancy (via dependency injection through MainActivity maybe?)

I think this is a worthwhile task, as the CI elements messing up production can harm our demo.

**Comment by joshuanianji** [comment]
Fixed in #175 but honestly, it brought more headache than fixes. Also CI still was erroring out.
