### ISSUE TITLE
Adding a dark and a light theme

### ISSUE THREAD

**Issue by kailashs2002** [CMPUT301F22T08/AndroidImpact#59]
I did some digging and found that creating a dark and a light colour scheme  for our app is not too difficult, and toggling between the two is as simple as changing a single attribute in the activity. 
We could have this option on the top right corner of MainActivity (so visible in all fragments) with a little moon/sun icon to hotswap between the two themes.

**Comment by joshuanianji** [comment]
That's a great idea, let's put it in the backlog; I'll add low priority right now as we're just using the colours from our figma
