### ISSUE TITLE
Discord Webhook: Fails when commit message has a quote

### ISSUE THREAD

**Issue by joshuanianji** [CMPUT301F22T08/AndroidImpact#77]
this is a bruh moment

See: https://github.com/CMPUT301F22T08/AndroidImpact/actions/runs/3374678657/jobs/5600545130
![Screenshot 2022-11-01 at 9 53 30 PM](https://user-images.githubusercontent.com/11809774/199391636-ffd11b3b-419e-4a5d-8eb7-28a9b83034bd.png)

idk if we can handle the commit message in bash honestly, too many different characters can break the script.

**Comment by joshuanianji** [comment]
Setting this to low priority but medium size, I think we might have to use another method for github actions, maybe a node script or something.

**Comment by LeCitrus** [comment]
@joshuanianji is this still an issue?

**Comment by joshuanianji** [comment]
Yup, but this is super low priority so i won't fix this right now (maybe errors out once every 30-40 commits). Maybe we need a `wontfix` label...
