### ISSUE TITLE
Cannot add items with expiry date as today's date

### ISSUE THREAD

**Issue by vedudx** [CMPUT301F22T08/AndroidImpact#92]
Do we want to disallow adding items which expire today ? Something like opened beer is encouraged to drink within a day. I think it makes sense to allow things like those as well. what do you guys think?

**Comment by joshuanianji** [comment]
i think we should allow that. Adding time would be too annoying, and we should only warn the user when the food's expiry is in the past.

**Comment by joshuanianji** [comment]
I think we changed this for testing.
